/// Model for budget-based travel recommendations
class BudgetRecommendation {
  final String countryCode;
  final String countryName;
  final String countryNameAr;
  final double estimatedTotalCost;
  final double flightCost;
  final double hotelCostPerNight;
  final double visaFee;
  final String visaStatus;
  final int maxStayDays;
  final double remainingBudget;
  final double savingsPercentage;
  final String affordabilityRating; // "Budget", "Standard", "Luxury"\n\n  BudgetRecommendation({\n    required this.countryCode,\n    required this.countryName,\n    required this.countryNameAr,\n    required this.estimatedTotalCost,\n    required this.flightCost,\n    required this.hotelCostPerNight,\n    required this.visaFee,\n    required this.visaStatus,\n    required this.maxStayDays,\n    required this.remainingBudget,\n    required this.savingsPercentage,\n    required this.affordabilityRating,\n  });\n\n  /// Calculate how many days user can stay with remaining budget\n  int get possibleDays {\n    if (hotelCostPerNight <= 0) return maxStayDays;\n    return (remainingBudget / hotelCostPerNight).toInt();\n  }\n\n  /// Sort destinations by affordability\n  static List<BudgetRecommendation> sortByAffordability(\n    List<BudgetRecommendation> recommendations,\n  ) {\n    return recommendations\n      ..sort((a, b) => b.remainingBudget.compareTo(a.remainingBudget));\n  }\n\n  /// Filter recommendations within budget\n  static List<BudgetRecommendation> filterAffordable(\n    List<BudgetRecommendation> recommendations,\n  ) {\n    return recommendations\n        .where((r) => r.remainingBudget >= 0)\n        .toList();\n  }\n\n  factory BudgetRecommendation.fromJson(Map<String, dynamic> json) {\n    return BudgetRecommendation(\n      countryCode: json['countryCode'] as String,\n      countryName: json['countryName'] as String,\n      countryNameAr: json['countryNameAr'] as String,\n      estimatedTotalCost: (json['estimatedTotalCost'] as num).toDouble(),\n      flightCost: (json['flightCost'] as num).toDouble(),\n      hotelCostPerNight: (json['hotelCostPerNight'] as num).toDouble(),\n      visaFee: (json['visaFee'] as num).toDouble(),\n      visaStatus: json['visaStatus'] as String,\n      maxStayDays: json['maxStayDays'] as int,\n      remainingBudget: (json['remainingBudget'] as num).toDouble(),\n      savingsPercentage: (json['savingsPercentage'] as num).toDouble(),\n      affordabilityRating: json['affordabilityRating'] as String,\n    );\n  }\n\n  Map<String, dynamic> toJson() => {\n        'countryCode': countryCode,\n        'countryName': countryName,\n        'countryNameAr': countryNameAr,\n        'estimatedTotalCost': estimatedTotalCost,\n        'flightCost': flightCost,\n        'hotelCostPerNight': hotelCostPerNight,\n        'visaFee': visaFee,\n        'visaStatus': visaStatus,\n        'maxStayDays': maxStayDays,\n        'remainingBudget': remainingBudget,\n        'savingsPercentage': savingsPercentage,\n        'affordabilityRating': affordabilityRating,\n      };\n}\n